package com.example.dndcharacterapp.models.level.api

data class ClassSpecific(
    val actionSurge: Int,
    val arcaneRecoveryLevel: Int,
    val auraRange: Int,
    val bardicInspirationDie: Int,
    val brutalCriticalDie: Int,
    val channelDivinityCharges: Int,
    val creatingSpellSlots: List<CreatingSpellSlot>,
    val destroyUndeadCr: Double,
    val extraAttacks: Int,
    val favoredEnemies: Int,
    val favoredTerrain: Int,
    val indomitableUses: Int,
    val invocationsKnown: Int,
    val kiPoints: Int,
    val magicSecretsMax5: Int,
    val magicSecretsMax7: Int,
    val magicSecretsMax9: Int,
    val martialArts: MartialArts,
    val metamagicKnown: Int,
    val mysticArcanumLevel6: Int,
    val mysticArcanumLevel7: Int,
    val mysticArcanumLevel8: Int,
    val mysticArcanumLevel9: Int,
    val rageCount: Int,
    val rageDamaageBonus: Int,
    val sneakAttack: SneakAttack,
    val songOfRestDie: Int,
    val sorceryPoints: Int,
    val unarmoredMovement: Int,
    val wildShapeFly: Boolean,
    val wildShapeMaxCr: Double,
    val wildShapeSwim: Boolean
)