package com.example.dndcharacterapp.models.character

data class Character(
    val _id: String,
    val name: String? = null,
    val level: Int? = null,
    val inspiration: Boolean = false,
    val background: String? = null,
    val race: Race? = null,
    val alignment: Alignment? = null,
    val hitPoints: HitPoints? = null,
    val hitDie: Array<HitDie>? = null,
    val deathSaves: DeathSaves? = null,
    val temporaryHitPoints: Int? = null,
    val exhaustion: Int? = null,
    val armorClass: ArmorClass? = null,
    val classes: Array<ClassItem>? = null,
    val experiencePoints: Int? = null,
    val stats: Array<Stat>? = null,
    val skillProficiencies: Array<SkillProficiency>? = null,
    val languages: Array<Language>? = null,
    val otherProficiencies: Array<Proficiency>? = null,
    val equipment: Array<Equipment>? = null,
    val coinPouch: Array<Coin>? = null,
    val features: Array<Feature>? = null,
    val traits: Array<Trait>? = null,
    val spellAbilities: Array<SpellAbility>? = null,
    val preparedSpells: Array<Spell>? = null,
    val knownSpells: Array<Spell>? = null,
    val passiveWisdom: Int? = null,
    val initiative: Int? = null,
    val speed: Int? = null,
    val proficiencyBonus: Int? = null,
    val savingThrows: Array<String>? = null,
    val personalityTrait: String? = null,
    val ideals: String? = null,
    val bonds: String? = null,
    val flaws: String? = null,
    val characterAppearance: String? = null,
    val characterBackstory: String? = null,
    val alliesOrganizations: String? = null,
    val symbol: String? = null
)