package com.example.dndcharacterapp.models.character

data class Character(
    val _id: String?,
    val name: String? = null,
    val level: Int? = null,
    val inspiration: Boolean = false,
    val background: String? = null,
    val race: Race? = null,
    val alignment: Alignment? = null,
    val hitPoints: HitPoints? = null,
    val hit_die: List<HitDie>? = null,
    val death_saves: DeathSaves? = null,
    val temporary_HitPoints: Int? = null,
    val exhaustion: Int? = null,
    val armor_Class: ArmorClass? = null,
    val classes: List<ClassItem>? = null,
    val experience_Points: Int? = null,
    val stats: List<Stat>? = null,
    val skill_proficiencies: List<SkillProficiency>? = null,
    val languages: List<Language>? = null,
    val other_proficiencies: List<Proficiency>? = null,
    val equipment: List<Equipment>? = null,
    val coin_pouch: List<Coin>? = null,
    val features: List<Feature>? = null,
    val traits: List<Trait>? = null,
    val spell_abilities: List<SpellAbility>? = null,
    val prepared_spells: List<Spell>? = null,
    val known_spells: List<Spell>? = null,
    val passive_wisdom: Int? = null,
    val initiative: Int? = null,
    val speed: Int? = null,
    val proficiency_bonus: Int? = null,
    val saving_throws: List<String>? = null,
    val personality_traits: String? = null,
    val ideals: String? = null,
    val bonds: String? = null,
    val flaws: String? = null,
    val character_appearance: String? = null,
    val character_backstory: String? = null,
    val allies_organizations: String? = null,
    val symbol: String? = null
)
