package com.example.dndcharacterapp.models.character

import io.realm.kotlin.ext.realmListOf
import io.realm.kotlin.types.RealmList

data class Character(
    //val _id: String,
    val username: String?,
    val name: String? = null,
    val level: Int? = null,
    val inspiration: Boolean = false,
    val background: String? = null,
    val race: Race? = null,
    val alignment: Alignment? = null,
    val hitPoints: HitPoints? = null,
    val hitDie: List<HitDie>? = null,
    val deathSaves: DeathSaves? = null,
    val temporaryHitPoints: Int? = null,
    val exhaustion: Int? = null,
    val armorClass: ArmorClass? = null,
    val classes: List<ClassItem>? = null,
    val experiencePoints: Int? = null,
    val stats: List<Stat>? = null,
    val skillProficiencies: List<SkillProficiency>? = null,
    val languages: List<Language>? = null,
    val otherProficiencies: List<Proficiency>? = null,
    val equipment: List<Equipment>? = null,
    val coinPouch: List<Coin>? = null,
    val features: List<Feature>? = null,
    val traits: List<Trait>? = null,
    val spellAbilities: List<SpellAbility>? = null,
    val preparedSpells: List<Spell>? = null,
    val knownSpells: List<Spell>? = null,
    val passiveWisdom: Int? = null,
    val initiative: Int? = null,
    val speed: Int? = null,
    val proficiencyBonus: Int? = null,
    var saving_throws: List<String> = listOf(""),
    val personalityTrait: String? = null,
    val ideals: String? = null,
    val bonds: String? = null,
    val flaws: String? = null,
    val characterAppearance: String? = null,
    val characterBackstory: String? = null,
    val alliesOrganizations: String? = null,
    val symbol: String? = null
)